### ISSUE TITLE
Define Data Source Connection at Build / Release Time

### ISSUE THREAD

**Issue by dodgy99** [maikvandergaag/msft-vsts-extensions#16]
Hi,

Do you know if its possible to change/define the data source (specifically thinking of a SQL Server Data Source) at build / release time using this extension. I currently have the issue when switching between dev/test/live environments having to manually update it each time before deploying.

Thanks

**Comment by maikvandergaag** [comment]
Hi,

I'm working on a release that will make this possible. Do not know yet when this release will be ready.

**Comment by maikvandergaag** [comment]
Released a new version of the extension as a new one that will be worked on in the feature:

https://marketplace.visualstudio.com/items?itemName=maikvandergaag.maikvandergaag-power-bi-actions
