### ISSUE TITLE
AzureRM.Profile not found. AzureRM module may not be fully installed.

### ISSUE THREAD

**Issue by ThijsVandaele** [maikvandergaag/msft-vsts-extensions#17]
Hi

When running your VSTS Task I stumbled upon an error.
##[error]Module 'AzureRM.Profile' not found. The 'AzureRM' module may not be fully installed. Running the  following PowerShell commands from an elevated session may resolve the issue: Import-Module AzureRM ; Install-AzureRM

I Think this is related to this issue (which is already be fixed) [https://github.com/Microsoft/vsts-tasks/issues/6720](url)

Thanks

**Comment by maikvandergaag** [comment]
Could you supply more information, version and environment. Besides that I would like to be able to reproduce the error.

**Comment by maikvandergaag** [comment]
If this is related to the Azure RBAC extension the issues should be fixed in version 1.2.0
