### ISSUE TITLE
Fail On Error does not trigger when applying User

### ISSUE THREAD

**Issue by hutchiee** [maikvandergaag/msft-vsts-extensions#18]
Fail On Error enabled, failure to find user does not trigger an error condition for the job

**log**
Resource group: MyAzure-rg
Groups: 
Users: myupn@sample.com
Role : Reader
Action : Users
Fail On Error : true
Setting RBAC for group: MyAzure-rg
Setting RBAC for specific users
Getting user myupn@sample.com
Can't find ad object: myupn@sample.com

**Comment by maikvandergaag** [comment]
Fixed in version 1.2.0
