### ISSUE TITLE
PowerBI Actions issue

### ISSUE THREAD

**Issue by Farzad-Jalali** [maikvandergaag/msft-vsts-extensions#28]
Dear Sir/Madam,

I love this extension, saved my time a lot.
I got a repository with many report and groups, it's working with most of the reports.
but there is a particular group which I only can upload 7 reports out of 9 reports.
as you see in the below screen:

![image](https://user-images.githubusercontent.com/3695669/43571528-19ac9288-9635-11e8-8a7e-da487be6bb98.png)

also, I have a group with only one file which it can't upload:
![image](https://user-images.githubusercontent.com/3695669/43571589-45e6c04e-9635-11e8-9434-c42db2deca4e.png)

** for both cases, I uploaded the files manually and they are uploading!

** what I suggest:**

I wonder if there was a way for you guys to get more details regarding the error messages and pass it to the logger.

**Comment by maikvandergaag** [comment]
Hi Farzad-Jalali, do you still encounter the issue?

**Comment by Farzad-Jalali** [comment]
Hi Maik,
I asked the BI team to rebuild the reports from scratch, also making a new group.
I think the mix of two actions actually fixed the problem and it's working just fine.
