### ISSUE TITLE
Azure RBAC - Trim spaces on group/user list

### ISSUE THREAD

**Issue by patpicos** [maikvandergaag/msft-vsts-extensions#33]
It would be good to remove spaces from the $groups / $users input. Leading spaces can cause 

> Get-AzureRmADGroup -SearchString

to not return values and failing the task. It was interesting to troubleshoot that today!

**Comment by maikvandergaag** [comment]
Hi Patrick, change is made in the develop branch will be publishing a new version of the extension today.

**Comment by patpicos** [comment]
Awesome! thanks Maik
