### ISSUE TITLE
Updating Dataset task - Bad Request

### ISSUE THREAD

**Issue by Prashanth-PS** [maikvandergaag/msft-vsts-extensions#35]
Getting this error while trying reset the dataset for a PowerBI report. The same task worked fine for uploading the Report but failing while trying update the Dataset for that report: 
 ##[error]The remote server returned an error: (400) Bad Request.

![image](https://user-images.githubusercontent.com/30700293/46704092-fcdf2800-cc85-11e8-976e-dca6e5a47a34.png)

**Comment by phil-tillotson-coop** [comment]
Just to add to this, I received the same error message when trying to update the connectionstring for a report that connects to azure analysis services, which may be relevant here (though you don't say what you were trying to update the connection to point to).

Having a peek at the code reveals that for updating connectionstrings  it uses [setalldatasetconnectionsingroup](https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/setalldatasetconnectionsingroup) , the docs for which explain this does not work for connections to SQL, AS, OData Feed, and SharePoint.

I suspect a different task type making use of a function calling [updatedatasourcesingroup](https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/updatedatasourcesingroup) would need to be used to update the server and database properties for SQL, AS, OData Feed, and SharePoint connections.

**Comment by Prashanth-PS** [comment]
OOOOOHHH!!!!!!

It is very annoying to find that the Data Source= parameter is mandatory for this task to get the Dataset updated in addition to setting the Server= parameter in the connection string. 
Whatever I have used is from Azure connection string directly and it is no where mentioned as a requirement 

After setting this parameter the Dataset update task is working

**Comment by johnsandersnl** [comment]
This issue is closed. But is this issue resolved or is it simply not possible to update a dataset connection to Azure Analysis Services? 
Provider=MSOLAP;Data Source=asazure://westeurope.asazure.windows.net/aasservername;Initial Catalog=databasename

**Comment by johnsandersnl** [comment]
Hi Prashanth-PS
Can you give an example of a working connection string to Azure Analysis Services? 
I cannot get this to work.

**Comment by Prashanth-PS** [comment]
> Hi Prashanth-PS
> Can you give an example of a working connection string to Azure Analysis Services?
> I cannot get this to work.

Hi Johnsandersnl

Here is the connection string which worked:
integrated security=False;data source=xxxx.database.windows.net;encrypt=True;connection timeout=30;initial catalog=xx;user id=xxx;server=tcp:xxxx.database.windows.net,1433;persist security info=False;multipleactiveresultsets=False;trustservercertificate=False;Password=xxxxx

However, on the PowerBI portal sometimes it shows as invalid credentials 👎

**Comment by johnsandersnl** [comment]
Hi Prashanth,
This looks like a connection string to SQL Azure. Do you know how to get this component to connect to Azure Analysis Services?

**Comment by maikvandergaag** [comment]
Hi johnsandernl,

is there any progress regarding your issue and what problems are you getting?

**Comment by ManikantaNani** [comment]
Hi,
I am also facing same issue . I am able to upload power BI report to an workspace but unable to update connection of dataset.
Getting Error: Bad request
